export const FETCHDATA = "FETCHDATA";
export const FILTERDATA = "FILTERDATA";
export const FILTERPRICE = "FILTERPRICE";

export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNUPFAILIURE = "SIGNUPFAILIURE";
export const SIGNINFAILIURE = "SIGNINFAILIURE";
